return {
  "nvim-treesitter/nvim-treesitter-textobjects",
  branch = "main",
  lazy = true,
  config = function()
    -- Note: In the new nvim-treesitter (main branch), textobjects configuration
    -- is handled differently. The plugin provides the motions and text objects
    -- automatically once loaded. We just need to set up the keymaps.

    local ts_repeat_move = require("nvim-treesitter-textobjects.repeatable_move")
    local ts_move = require("nvim-treesitter-textobjects.move")
    local ts_swap = require("nvim-treesitter-textobjects.swap")
    local ts_select = require("nvim-treesitter-textobjects.select")

    -- Text object selection keymaps
    vim.keymap.set({ "x", "o" }, "a=", function()
      ts_select.select_textobject("@assignment.outer", "textobjects")
    end, { desc = "Select outer part of an assignment" })
    vim.keymap.set({ "x", "o" }, "i=", function()
      ts_select.select_textobject("@assignment.inner", "textobjects")
    end, { desc = "Select inner part of an assignment" })
    vim.keymap.set({ "x", "o" }, "l=", function()
      ts_select.select_textobject("@assignment.lhs", "textobjects")
    end, { desc = "Select left hand side of an assignment" })
    vim.keymap.set({ "x", "o" }, "r=", function()
      ts_select.select_textobject("@assignment.rhs", "textobjects")
    end, { desc = "Select right hand side of an assignment" })

    vim.keymap.set({ "x", "o" }, "a:", function()
      ts_select.select_textobject("@property.outer", "textobjects")
    end, { desc = "Select outer part of an object property" })
    vim.keymap.set({ "x", "o" }, "i:", function()
      ts_select.select_textobject("@property.inner", "textobjects")
    end, { desc = "Select inner part of an object property" })
    vim.keymap.set({ "x", "o" }, "l:", function()
      ts_select.select_textobject("@property.lhs", "textobjects")
    end, { desc = "Select left part of an object property" })
    vim.keymap.set({ "x", "o" }, "r:", function()
      ts_select.select_textobject("@property.rhs", "textobjects")
    end, { desc = "Select right part of an object property" })

    vim.keymap.set({ "x", "o" }, "aa", function()
      ts_select.select_textobject("@parameter.outer", "textobjects")
    end, { desc = "Select outer part of a parameter/argument" })
    vim.keymap.set({ "x", "o" }, "ia", function()
      ts_select.select_textobject("@parameter.inner", "textobjects")
    end, { desc = "Select inner part of a parameter/argument" })

    vim.keymap.set({ "x", "o" }, "ai", function()
      ts_select.select_textobject("@conditional.outer", "textobjects")
    end, { desc = "Select outer part of a conditional" })
    vim.keymap.set({ "x", "o" }, "ii", function()
      ts_select.select_textobject("@conditional.inner", "textobjects")
    end, { desc = "Select inner part of a conditional" })

    vim.keymap.set({ "x", "o" }, "al", function()
      ts_select.select_textobject("@loop.outer", "textobjects")
    end, { desc = "Select outer part of a loop" })
    vim.keymap.set({ "x", "o" }, "il", function()
      ts_select.select_textobject("@loop.inner", "textobjects")
    end, { desc = "Select inner part of a loop" })

    vim.keymap.set({ "x", "o" }, "af", function()
      ts_select.select_textobject("@call.outer", "textobjects")
    end, { desc = "Select outer part of a function call" })
    vim.keymap.set({ "x", "o" }, "if", function()
      ts_select.select_textobject("@call.inner", "textobjects")
    end, { desc = "Select inner part of a function call" })

    vim.keymap.set({ "x", "o" }, "am", function()
      ts_select.select_textobject("@function.outer", "textobjects")
    end, { desc = "Select outer part of a method/function definition" })
    vim.keymap.set({ "x", "o" }, "im", function()
      ts_select.select_textobject("@function.inner", "textobjects")
    end, { desc = "Select inner part of a method/function definition" })

    vim.keymap.set({ "x", "o" }, "ac", function()
      ts_select.select_textobject("@class.outer", "textobjects")
    end, { desc = "Select outer part of a class" })
    vim.keymap.set({ "x", "o" }, "ic", function()
      ts_select.select_textobject("@class.inner", "textobjects")
    end, { desc = "Select inner part of a class" })

    -- Swap text objects
    vim.keymap.set("n", "<leader>na", function()
      ts_swap.swap_next("@parameter.inner")
    end, { desc = "Swap parameter with next" })
    vim.keymap.set("n", "<leader>n:", function()
      ts_swap.swap_next("@property.outer")
    end, { desc = "Swap property with next" })
    vim.keymap.set("n", "<leader>nm", function()
      ts_swap.swap_next("@function.outer")
    end, { desc = "Swap function with next" })

    vim.keymap.set("n", "<leader>pa", function()
      ts_swap.swap_previous("@parameter.inner")
    end, { desc = "Swap parameter with previous" })
    vim.keymap.set("n", "<leader>p:", function()
      ts_swap.swap_previous("@property.outer")
    end, { desc = "Swap property with previous" })
    vim.keymap.set("n", "<leader>pm", function()
      ts_swap.swap_previous("@function.outer")
    end, { desc = "Swap function with previous" })

    -- Movement keymaps
    vim.keymap.set({ "n", "x", "o" }, "]f", function()
      ts_move.goto_next_start("@call.outer")
    end, { desc = "Next function call start" })
    vim.keymap.set({ "n", "x", "o" }, "]m", function()
      ts_move.goto_next_start("@function.outer")
    end, { desc = "Next method/function def start" })
    vim.keymap.set({ "n", "x", "o" }, "]c", function()
      ts_move.goto_next_start("@class.outer")
    end, { desc = "Next class start" })
    vim.keymap.set({ "n", "x", "o" }, "]i", function()
      ts_move.goto_next_start("@conditional.outer")
    end, { desc = "Next conditional start" })
    vim.keymap.set({ "n", "x", "o" }, "]l", function()
      ts_move.goto_next_start("@loop.outer")
    end, { desc = "Next loop start" })

    vim.keymap.set({ "n", "x", "o" }, "]F", function()
      ts_move.goto_next_end("@call.outer")
    end, { desc = "Next function call end" })
    vim.keymap.set({ "n", "x", "o" }, "]M", function()
      ts_move.goto_next_end("@function.outer")
    end, { desc = "Next method/function def end" })
    vim.keymap.set({ "n", "x", "o" }, "]C", function()
      ts_move.goto_next_end("@class.outer")
    end, { desc = "Next class end" })
    vim.keymap.set({ "n", "x", "o" }, "]I", function()
      ts_move.goto_next_end("@conditional.outer")
    end, { desc = "Next conditional end" })
    vim.keymap.set({ "n", "x", "o" }, "]L", function()
      ts_move.goto_next_end("@loop.outer")
    end, { desc = "Next loop end" })

    vim.keymap.set({ "n", "x", "o" }, "[f", function()
      ts_move.goto_previous_start("@call.outer")
    end, { desc = "Prev function call start" })
    vim.keymap.set({ "n", "x", "o" }, "[m", function()
      ts_move.goto_previous_start("@function.outer")
    end, { desc = "Prev method/function def start" })
    vim.keymap.set({ "n", "x", "o" }, "[c", function()
      ts_move.goto_previous_start("@class.outer")
    end, { desc = "Prev class start" })
    vim.keymap.set({ "n", "x", "o" }, "[i", function()
      ts_move.goto_previous_start("@conditional.outer")
    end, { desc = "Prev conditional start" })
    vim.keymap.set({ "n", "x", "o" }, "[l", function()
      ts_move.goto_previous_start("@loop.outer")
    end, { desc = "Prev loop start" })

    vim.keymap.set({ "n", "x", "o" }, "[F", function()
      ts_move.goto_previous_end("@call.outer")
    end, { desc = "Prev function call end" })
    vim.keymap.set({ "n", "x", "o" }, "[M", function()
      ts_move.goto_previous_end("@function.outer")
    end, { desc = "Prev method/function def end" })
    vim.keymap.set({ "n", "x", "o" }, "[C", function()
      ts_move.goto_previous_end("@class.outer")
    end, { desc = "Prev class end" })
    vim.keymap.set({ "n", "x", "o" }, "[I", function()
      ts_move.goto_previous_end("@conditional.outer")
    end, { desc = "Prev conditional end" })
    vim.keymap.set({ "n", "x", "o" }, "[L", function()
      ts_move.goto_previous_end("@loop.outer")
    end, { desc = "Prev loop end" })

    -- Repeat movement with ; and ,
    -- ensure ; goes forward and , goes backward regardless of the last direction
    vim.keymap.set({ "n", "x", "o" }, ";", ts_repeat_move.repeat_last_move_next)
    vim.keymap.set({ "n", "x", "o" }, ",", ts_repeat_move.repeat_last_move_previous)

    -- vim way: ; goes to the direction you were moving.
    -- vim.keymap.set({ "n", "x", "o" }, ";", ts_repeat_move.repeat_last_move)
    -- vim.keymap.set({ "n", "x", "o" }, ",", ts_repeat_move.repeat_last_move_opposite)

    -- Optionally, make builtin f, F, t, T also repeatable with ; and ,
    vim.keymap.set({ "n", "x", "o" }, "f", ts_repeat_move.builtin_f_expr, { expr = true })
    vim.keymap.set({ "n", "x", "o" }, "F", ts_repeat_move.builtin_F_expr, { expr = true })
    vim.keymap.set({ "n", "x", "o" }, "t", ts_repeat_move.builtin_t_expr, { expr = true })
    vim.keymap.set({ "n", "x", "o" }, "T", ts_repeat_move.builtin_T_expr, { expr = true })
  end,
}
