# ~/.config/starship.toml

palette = "catppuccin_mocha"

[character]
vimcmd_symbol = '[❮](bold blue)'
# only Insert/Normal mode for zsh:
# https://github.com/starship/starship/issues/625#issuecomment-732454148
#vimcmd_visual_symbol = '[V](bold purple) '

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
#symbol = "  "

[golang]
format = '[ $version](bold cyan) '

[kubernetes]
symbol = '☸'
disabled = false
detect_files = ['k8s', 'Dockerfile']
detect_extensions = ['yaml']
format = '[$symbol$context( \($namespace\))]($style) '
[kubernetes.context_aliases]
#'arn:aws:eks:us-west-2:123:cluster/gal-kub-demo-cluster' = 'gal'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
