local mark = require 'harpoon.mark'
local ui = require 'harpoon.ui'

vim.keymap.set('n', '<leader>hi', mark.add_file, { desc = '[H]arpoon add [I]tem' })
vim.keymap.set('n', '<leader>hm', ui.toggle_quick_menu, { desc = '[H]arpoon [M]enu' })

vim.keymap.set('n', '<leader>ha', function()
  ui.nav_file(1)
end, { desc = '[H]arpoon 1st file' })
vim.keymap.set('n', '<leader>hs', function()
  ui.nav_file(2)
end, { desc = '[H]arpoon 2nd file' })
vim.keymap.set('n', '<leader>hd', function()
  ui.nav_file(3)
end, { desc = '[H]arpoon 3rd file' })
vim.keymap.set('n', '<leader>hf', function()
  ui.nav_file(4)
end, { desc = '[H]arpoon 4th file' })
vim.keymap.set('n', '<leader>hg', function()
  ui.nav_file(5)
end, { desc = '[H]arpoon 5th file' })
vim.keymap.set('n', '<leader>hh', function()
  ui.nav_file(6)
end, { desc = '[H]arpoon 6th file' })
vim.keymap.set('n', '<leader>hj', function()
  ui.nav_file(7)
end, { desc = '[H]arpoon 7th file' })
vim.keymap.set('n', '<leader>hk', function()
  ui.nav_file(8)
end, { desc = '[H]arpoon 8th file' })
vim.keymap.set('n', '<leader>hl', function()
  ui.nav_file(9)
end, { desc = '[H]arpoon 9th file' })
vim.keymap.set('n', '<leader>h;', function()
  ui.nav_file(10)
end, { desc = '[H]arpoon 10th file' })
