require("items.apple")
require("items.menus")
require("items.aerospace")
require("items.front_app")

require("items.today")
require("items.keyboard")
-- require("items.calendar")
require("items.widgets")
require("items.media")
