#!/bin/bash

# Requirements of Arch Linux installation:
# - wget

# wget -qO- https://raw.githubusercontent.com/aimestereo/dotfiles/refs/heads/main/utils/arch-install | bash

ROOT_DIR=~/projects/my
mkdir -p "$ROOT_DIR"
cd "$ROOT_DIR"

# Install Nix package manager
sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon

# Install Home Manager
nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
nix-channel --update
nix-shell '<home-manager>' -A install
. "$HOME"/.nix-profile/etc/profile.d/hm-session-vars.sh

# Install temporary packages
nix-env -iA nixpkgs.git

# Clone public dotfiles repository
cd "$ROOT_DIR"
git clone git@github.com:aimestereo/dotfiles.git
cd dotfiles
make nix-arch
make symlinks

# Tmux Plugin Manager (TPM)
# todo: marry with nix
mkdir -p ~/.config/tmux/plugins
git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm

# ~/.local/share/omarchy/install.sh

# Clone private dotfiles repository
ssh-keygen -t ed25519 -C "aimestereo@gmail.com Arch"
echo "Register the following SSH public key with GitHub:"
cat ~/.ssh/id_ed25519.pub
read -p "Press [Enter] key after registering the SSH key with GitHub..."

cd "$ROOT_DIR"
git clone git@github.com:aimestereo/dotfiles-private.git
cd dotfiles-private
make symlinks
