#!/bin/bash

# Requirements of Arch Linux installation:
# - wget

# wget -qO- https://raw.githubusercontent.com/aimestereo/dotfiles/refs/heads/main/utils/arch-install | bash

# Generate SSH key for GitHub
ssh-keygen -t ed25519 -C "aimestereo@gmail.com Arch"
echo "Register the following SSH public key with GitHub:"
cat ~/.ssh/id_ed25519.pub
read -p "Press [Enter] key after registering the SSH key with GitHub..."

# Install Nix package manager
sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon
source ~/.bashrc
nix --version

# Install temporary packages
nix-env -iA nixpkgs.git nixpkgs.stow

ROOT_DIR=~/Work/my
mkdir -p "$ROOT_DIR"
cd "$ROOT_DIR"

# Clone required repositories
git clone git@github.com:aimestereo/obsidian.git
git clone git@github.com:aimestereo/dotfiles.git
git clone git@github.com:aimestereo/dotfiles-private.git

cd "$ROOT_DIR/dotfiles"
make symlinks
source ~/.bashrc

# Clean up temporary packages, they will be managed via Nix Home Manager
nix-env -e git stow
make nix-arch

cd "$ROOT_DIR/dotfiles-private"
make symlinks
