#!/usr/bin/env bash

set -euo pipefail

utils/install

# Install homebrew
git config --global http.version HTTP/1.1
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
